### ISSUE TITLE
Documentation doesn't say what the example and Quickstart cases are simulating

### ISSUE THREAD

**Issue by blakeaw** [mpievolbio-scicomp/cancer_sim#10]
Hello,

This issue is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/2436

For the example you provided in the README and also for the one in the Quickstart it looks like there isn't information about what cases they are actually simulating. For example, are the parameters modeling a specific tumor type? Or is this essentially just a toy-model set of parameters? I think it might be good to mention this in the documentation/examples.

**Comment by CFGrote** [comment]
@lopasic, can you please review PR #15, in particular check scientific
background of examples both in README and in the notebook.

thanks! c

**Comment by blakeaw** [comment]
Thanks for addressing this issue. I'll go ahead and close.
For future reference, the Quickstart example and its description are in the documentation here: https://cancer-sim.readthedocs.io/en/master/include/notebooks/quickstart_example.html
