### ISSUE TITLE
Fix binder link

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/cancer_sim#4]
The binder link in the readme and paper should point to the github repo, not gitlab.
- [x] Fix link
- [x] Test notebook is correctly launched,
- [x] Test notebook is up to date
- [x] Test notebook executes

**Comment by lopasic** [comment]
These are instructions for me? I will look into

**Comment by CFGrote** [comment]
hi luka,
no, this was just meant for myself, so I knew where I left off yesterday.

carsten
