### ISSUE TITLE
Missing pip install of casim package in Installation directions?

### ISSUE THREAD

**Issue by blakeaw** [mpievolbio-scicomp/cancer_sim#5]
I followed the steps to install casim using a conda env, but upon running the tests I got the following error:
 
Traceback (most recent call last):
  File "casim_test.py", line 4, in <module>
    from casim import casim
ModuleNotFoundError: No module named 'casim'

I think the Installation instructions may be missing an explicit step. I tried running `pip install .` from the cancer_sim directory and casim installed in my environment and then the tests ran OK.

**Comment by jenzopr** [comment]
You might also want to create a console script entrypoint in `setup.py` and then uploade to pip and/or create a conda package. Installation instructions and access to the high level function would simplify drastically.

**Comment by blakeaw** [comment]
This issue is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/2436

**Comment by CFGrote** [comment]
fixed by PR #13.

**Comment by blakeaw** [comment]
Thanks!
