### ISSUE TITLE
Additional high level documentation for simulation outputs

### ISSUE THREAD

**Issue by blakeaw** [mpievolbio-scicomp/cancer_sim#8]
Hello,

This issue is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/2436

I'd recommend adding some additional high-level documentation on what the simulation outputs are for runs with `casim.casim`. Currently, it looks like the only related documentation is the following under the examples: 'Results will be stored in the newly created directory `sim_out/`.'  However, there doesn't appear to be any documentation on what the expected output file-structure is in the `sim_out` out directory or what information each output file contains. It may also be helpful for new users if you give some hints on how to follow up with analyzing those outputs - assuming it's not entirely self-explanatory in the output file descriptions.

**Comment by blakeaw** [comment]
Similarly, for outputs generated by `casim.CancerSimulator.run`.

**Comment by blakeaw** [comment]
Ok, I re-read the Background in the README and I see that towards the end it says "After the simulation, the tumour matrix, and the lists of lineages and frequencies of each mutation in the tumour are exported to files." So you can probably just restate this under the high-level functionality description along with a more detailed layout of the output directory structure and filenames generated when you run casim. And you might also add this information to the quickstart example too, just to remind users again what to expect as outputs in case they missed it elsewhere (like I did).

**Comment by CFGrote** [comment]
> Similarly, for outputs generated by `casim.CancerSimulator.run`.

done (4fb51ca).

**Comment by blakeaw** [comment]
Thanks! Since this issue has been addressed I'll go ahead an close.
